### ISSUE TITLE
Add possible undo method for accidental flagging

### ISSUE THREAD

**Issue by Ferrariic** [Bot-detector/bot-detector#135]
0.5-1% of the time, players will misclick options and accidentally click the wrong button. The ability to undo an option would fix this.

**Comment by Cyborger1** [comment]
The feedback and flags are sent immediately to the server when clicked, undoing them would require opening up some sort of API path for deleting them on our side. Such an API would be dangerous to have opened without any authentication.

We can tolerate a small error due to misclicks, players should just be a little more mindful. I'm closing this issue.
