### ISSUE TITLE
Zalcano bot detection seems broken

### ISSUE THREAD

**Issue by Nosaiii** [Bot-detector/bot-detector#145]
It seems the detection whether someone is a Zalcano bot is broken. It almost always shows for anyone that he/she is a Zalcano bot. In addition to that, even players who have never done Zalcano are considered Zalcano bots. The percentage is quite small, but still it seems that the bot detection regarding Zalcano is broken.

The player below has 0 kc on Zalcano and is still considered a Zalcano bot.
![image](https://user-images.githubusercontent.com/57220739/129895516-04888f11-1583-48b3-99f8-6a37bf1dad71.png)

**Comment by Ferrariic** [comment]
Hey there :) Thanks for your post and concern.

The Zalcano bot label (As well as other bot-like labels we've tried to implement) all suffer from the same situation: They must also take stats into account. For a machine learning algorithm which cannot determine the difference between stats and boss KC, this can be quite confusing to the system, especially when it sees an account that has >70 base stats, but no Zalcano KC. On paper, the system believes that there may be some chance of the account being a zalcano bot based upon **stats** and **boss kc**. 

Since the percentage is so small, despite the consideration being quite spread out among multiple accounts, it's really not a concern for us as that label works very well at this time to detect Zalcano Goldfarmers and Zalcano bot-like accounts. 

To give a bit of a perspective into what the system is thinking when it sees an account that 'could' do zalcano but doesn't have zalcano kc:
1) "Wow, this guy has all the stats for zalcano, but he doesn't have any zalcano kc..."
2) "Maybe there's a chance (<1%) that he's a zalcano bot, I think so, so I'll put it down for safe measure"

So usually if the account's breakdown doesn't indicate something severe, like >99% zalcano bot, we really just take it as part of the noise of the system, which is quite normal for ML. 

Thanks :) Let me know if you have any other questions or concerns.

**Comment by Ferrariic** [comment]
Closing this issue for now. Thanks!

**Comment by extreme4all** [comment]
the % you see in your example means that your stats correlate 98.33% with a real player and 1.33% with a zalcano bot.
Assuming this is a real player the prediction would be correct the primary prediction says that you are a real player.

**Comment by extreme4all** [comment]
-- keep this open to prevent repeat questions

**Comment by Ashtontanner69** [comment]
You could just resolve the prediction client side, taking out zalcano bot % < 2 since this seems to be triggering enough people to ask about it. redistributing the % among other results.

Since this would technically show false results in the case they are a bot you could only apply this if the results are purely Real player, and zalcano bot.

Hardfixing things like this is defiantly not the best way, but its all about UX right?

**Comment by Ferrariic** [comment]
We'd probably be more likely to add a lower limit cap to the plugin side of things, and then default that to 5% to omit some low percent noise. That could work potentially as an option which would also allow players to vary the percentage. Though @Cyborger1 would know more about how feasible such implementation would be

**Comment by Cyborger1** [comment]
It wouldn't be very hard but people are just gonna turn it down and be confused at the low percents or turn it up and be also confused, but at the missing percents instead. I think we just ought to leave it as is to be honest.

I mean, remember when the API had the aggressive rounding on prediction %s? We had some people with a lot of the noise you're talking about complaining their total only added up to 90% for example.

**Comment by Ferrariic** [comment]
Yeah tbh, no matter what we do besides improving the machine learning output, people will have concerns :p unfortunately some noise is unavoidable and is part of the process.

**Comment by Ashtontanner69** [comment]
> I mean, remember when the API had the aggressive rounding on prediction %s? We had some people with a lot of the noise you're talking about complaining their total only added up to 90% for example.

The total could be adjusted to 100% using ratios. IMO lots of noise looks better than none but I see what your getting at. Overall this is a pretty small thing. well said @Ferrariic
